// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWv4yVNrQgOb8oIovMdqp7JL_PS82jnSo',
    appId: '1:443999477170:web:b6c4bf13eb2104e15e58ab',
    messagingSenderId: '443999477170',
    projectId: 'resqube-31f3c',
    authDomain: 'resqube-31f3c.firebaseapp.com',
    storageBucket: 'resqube-31f3c.appspot.com',
    measurementId: 'G-T2D8Z3565S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhi5DfwJM7ZDFsvtIxuLuwOm12-Ghr2tI',
    appId: '1:443999477170:android:4cc955474b89a31b5e58ab',
    messagingSenderId: '443999477170',
    projectId: 'resqube-31f3c',
    storageBucket: 'resqube-31f3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCNQGSQwh9zIB810a9NGIMXzwDX_AiBZM',
    appId: '1:443999477170:ios:03f01758b343184f5e58ab',
    messagingSenderId: '443999477170',
    projectId: 'resqube-31f3c',
    storageBucket: 'resqube-31f3c.appspot.com',
    iosBundleId: 'com.example.kren',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCNQGSQwh9zIB810a9NGIMXzwDX_AiBZM',
    appId: '1:443999477170:ios:1d0d2d3a60cc49615e58ab',
    messagingSenderId: '443999477170',
    projectId: 'resqube-31f3c',
    storageBucket: 'resqube-31f3c.appspot.com',
    iosBundleId: 'com.example.kren.RunnerTests',
  );
}
